### ISSUE TITLE
[Request]  Bot Ui changes and misc features

### ISSUE THREAD

**Issue by Jarvis991** [Dawn-India/Z-Mirror#19]
Kindly add:
>Some buttons (ss given) (clicking on page no button shows stats)
>If Leeched file completion msg gives files names as 1. file 1   2. file 2   3. file 3 (in an index form such that clicking on file name  sends us to the leeched file)
>Speed test with pic ( missing it cuz nearly all repos removed it)
![image](https://user-images.githubusercontent.com/97823396/179737952-7db271e5-5815-4577-a713-fadfde37ccd9.png)
![image](https://user-images.githubusercontent.com/97823396/179737251-1952685b-4102-4475-b52b-a33f85a2ef29.png)
![image](https://user-images.githubusercontent.com/97823396/179737430-f547a47d-f713-4e4d-b13d-0c104f2039c0.png)

**Comment by Dawn-India** [comment]
Didn't found those things necessery right now, will think about it later.
