### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by I-Am-HappyBoy** [Dawn-India/Z-Mirror#21]
1) Auto Detect Feature or 

Put One Command And Select Commands Manually By Pressing Inline Button. (Like DriveCok Group).

2) Torrent, Google Drive, Renaming Feature Needed While Mirroring/Leeching.

3) Appdrive Direct Leech Needed Like GDToT.

4) If Possible Support Multcloud So That We Can Select Different Cloud While Mirroring As Gdrive Ending It's Unlimited Storage Feature For Free and Not Everyone Could afford to buy Storage every Month.

5) MediaInfo Feature Needed For Telegram Files.

6) If Possible Add Multiple Drive Support Feature Not Only Cloning But Also Leeching Directly Like GDToT.

7) Add A Var In Config Which Can Replace All "@Z_Mirror" & Your Name "Dawn" In Bot Statistics Button With WhatEver We Wrote In That Var.

8) Add Free Uptobox Token Support As Whisky Said His New Tutorial Video (https://www.youtube.com/watch?v=IUmq1paCiHI).

**Comment by Dawn-India** [comment]
Will try 3 & 7 on next update, rest are in future.
