### ISSUE TITLE
Clone Not working 

### ISSUE THREAD

**Issue by teamhdt-bsnl** [Dawn-India/Z-Mirror#22]
Only Drive link clone working

Gdtot and Appdrive clone not working

Appdrive clone error - link not recognised (Send Gdrive or GDToT/AppDrive/DriveApp link along with command or by replying to the link by command)

Gdtot clone error - all Gdtot links same error (ERROR: Try in your broswer, mostly file not found or user limit exceeded!)

**Comment by Dawn-India** [comment]
![Screenshot_2022-07-20-12-45-40-250_org telegram messenger web](https://user-images.githubusercontent.com/61337422/179920423-328b220a-7308-45c9-95a3-1ce421de1c9c.jpg)
Working perfectly.

**Comment by teamhdt-bsnl** [comment]
Don't test in already deployed bot

Fork and deploy a new bot and check whether it is working?
