### ISSUE TITLE
What's problem on ffmpeg?

### ISSUE THREAD

**Issue by nodirhajiev** [Dawn-India/Z-Mirror#37]
`bot.helper.mirror_utils.upload_utils.pyrogramEngine - ERROR - [Errno 2] No such file or directory: 'ffmpeg' Path: /usr/src/app/downloads/57351/Life_could_be_a_dream..._Bounce.webm
bot - INFO - Cleaning Download: /usr/src/app/downloads/50
bot - ERROR - GID 18b0800376f3c707 is not found onDownloadStart: 18b0800376f3c707 stop duplicate and size check didn't pass`

Many files giving error on leeching. What's problem on ffmpeg?

**Comment by Dawn-India** [comment]
install the ffmpeg again.

**Comment by nodirhajiev** [comment]
How to install? on your requirements doesn't exist this ffmpeg.

**Comment by nodirhajiev** [comment]
> install the ffmpeg again.

How to install? on your requirements doesn't exist this ffmpeg.

**Comment by Dawn-India** [comment]
it's there on docker image, no need to add in requirements.
Re-deploy your bot.
