### ISSUE TITLE
#Feature Request 

### ISSUE THREAD

**Issue by Emilyoftg** [Dawn-India/Z-Mirror#52]
Hello Bro 😃,

Can You Add Automatic Mirror For Magnets, Direct links & Tg Files. A Setup Which automatically detectes the links and files we send in group and mirrors it for us. It would be Great Help If You Add That Feature in Your repo 😅

**Comment by Dawn-India** [comment]
Auto detect is not a group friendly feature. It creates many problems.
It's good for personal bot only.

**Comment by Emilyoftg** [comment]
Then Plzz create a personal branch for it or plzz help me to add those features 😁
