### ISSUE TITLE
Consider

### ISSUE THREAD

**Issue by Emilyoftg** [Dawn-India/Z-Mirror#53]
Then Plzz create a personal branch for it or plzz help me to add those features 😁

_Originally posted by @Emilyoftg in https://github.com/Dawn-India/Z-Mirror/issues/52#issuecomment-1206630463_

**Comment by Dawn-India** [comment]
Code is already there in this repo: https://github.com/Emilyoftg/FileAutoMirror
Use some logical sense and copy it. Simple.

**Comment by Emilyoftg** [comment]
> Code is already there in this repo: https://github.com/Emilyoftg/FileAutoMirror Use some logical sense and copy it. Simple.

This is now flagged by herokku so if you have any idea plzz help me for it 😓
